//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTEv2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MetalprenBDEntities : DbContext
    {
        public MetalprenBDEntities()
            : base("name=MetalprenBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_MenuesxUsuario_Result> sp_MenuesxUsuario(Nullable<int> codigoUsuario)
        {
            var codigoUsuarioParameter = codigoUsuario.HasValue ?
                new ObjectParameter("codigoUsuario", codigoUsuario) :
                new ObjectParameter("codigoUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MenuesxUsuario_Result>("sp_MenuesxUsuario", codigoUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_SubMenuesxUsuario_Result> sp_SubMenuesxUsuario(Nullable<int> codigoUsuario, Nullable<int> padre)
        {
            var codigoUsuarioParameter = codigoUsuario.HasValue ?
                new ObjectParameter("codigoUsuario", codigoUsuario) :
                new ObjectParameter("codigoUsuario", typeof(int));
    
            var padreParameter = padre.HasValue ?
                new ObjectParameter("padre", padre) :
                new ObjectParameter("padre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SubMenuesxUsuario_Result>("sp_SubMenuesxUsuario", codigoUsuarioParameter, padreParameter);
        }
    }
}
